meta-xt-domx/recipes-extended/xen/xen-source.inc
It has been done to avoid overriding of the SRC_URI in multiple recipes and allow to
set the URL in [prod].yaml file. Now it is not necessary to implement the recipe(s)
just to update the source of xen.
Signed-off-by: Ihor Usyk <ihor_usyk@epam.com>
=> xen: add variable XEN_URL to customize the xen source.

meta-xt-driver-domain/recipes-extended/displaymanager/files/display-manager.service, meta-xt-driver-domain/recipes-extended/displbe/files/displbe.service
Weston service is using /etc/default/weston file to populate weston
environment to the service. Displaymanager and displ_be should use the
same file because they are dependend from weston.
Signed-off-by: Oleksii Moisieiev <oleksii_moisieiev@epam.com>
=> displaymanager: switch displbe and displaymanager to weston env file

meta-xt-driver-domain/recipes-extended/sndbe/files/sndbe.service, meta-xt-driver-domain/recipes-extended/sndbe/sndbe_git.bb, meta-xt-driver-domain/recipes-multimedia/pulseaudio/files/pulseaudio.service, meta-xt-driver-domain/recipes-multimedia/pulseaudio/pulseaudio_%.bbappend
Configure sndbe based on DISTRO_FEATURE entry to support alsa or
pulseaudio.
Signed-off-by: Oleksii Moisieiev <oleksii_moisieiev@epam.com>
=> sndbe: update recipe to support both pulseaudio and alsa

meta-xt-control-domain/recipes-guest/doma/u-boot-android.bb
Some products need specific source branches for doma
u-boot. Provide a mechanism to be able to override
u-boot source url.
Signed-off-by: Andrii Chepurnyi <andrii_chepurnyi@epam.com>
=> doma: provide the ability to override u-boot source url

meta-xt-driver-domain/recipes-graphics/images/core-image-weston.bbappend
`sndbe` and `camerabe` are product specific things, so should
be added in product's bbappend-files.
Signed-off-by: Ruslan Shymkevych <ruslan_shymkevych@epam.com>
=> domd: Remove product specific packages

meta-xt-driver-domain/recipes-connectivity/xen-network/files/bridge-up-notification.service, meta-xt-driver-domain/recipes-connectivity/xen-network/xen-network.bb, meta-xt-driver-domain/recipes-extended/block/block.bb, meta-xt-driver-domain/recipes-extended/block/files/block-up-notification.service, meta-xt-driver-domain/recipes-extended/camerabe/camerabe_git.bb, meta-xt-driver-domain/recipes-extended/camerabe/files/camerabe.service, meta-xt-driver-domain/recipes-extended/displbe/displbe_git.bb, meta-xt-driver-domain/recipes-extended/displbe/files/displbe.service, meta-xt-driver-domain/recipes-extended/sndbe/files/sndbe.service, meta-xt-driver-domain/recipes-extended/sndbe/sndbe_git.bb, meta-xt-driver-domain/recipes-extended/virtio-disk/files/virtio-disk.service, meta-xt-driver-domain/recipes-extended/virtio-disk/virtio-disk.bb
Hello,
this pull request introduces both install and startup dependencies over xenstore for PV backends. This is needed for correct execution of the ExecStartPost, ExecPost and ExecStopPost actions declared inside the systemd services for the backends.
The issue that triggered the need for this pull request is a timed-out shutdown of the sndbe service due to the fact that the xenstored service was stopped before it (and thus both the ExecStop and ExecStopPost actions were failing).
Also, I'm pretty sure that after this modification the "ExecStartPre=/bin/sleep 1" line inside sndbe.serivce can be removed (but I'm not sure why it's there, so this is not performed in current pull request).
=> Xenstore dependencies

meta-xt-driver-domain/recipes-extended/displbe/displbe_git.bb
The common product should use master as a
source branch for development.
Signed-off-by: Andrii Chepurnyi <andrii_chepurnyi@epam.com>
=> domd, displbe: change revision to master

meta-xt-driver-domain/recipes-extended/camerabe/camerabe_git.bb, meta-xt-driver-domain/recipes-extended/displaymanager/displaymanager_git.bb, meta-xt-driver-domain/recipes-extended/displbe/displbe_git.bb, meta-xt-driver-domain/recipes-extended/sndbe/sndbe_git.bb
Use PACKAGECONFIG mechanism whenever possible in meta-xt-control-domain, to simplify configuration done by platform-specific layers. Default PACKAGECONFIGs reflect previous static configuration.
It shall be noted that bbappends defined in layers building on top of this will work as before only if they uses `EXTRA_OECMAKE_append` to modify the EXTRA_OECMAKE variable, but will not work if they uses `EXTRA_OECMAKE +=` (as values coming from the PACKAGECONFIG mechanism will be appended).
=> domd: use PACKAGECONFIG whenever possible

meta-xt-control-domain/recipes-guest/doma/doma.bb
If we do not use DomA then XT_DOMA_CONFIG_NAME is not defined.
This results in attempt to calculate CRC for incorrect file
`file://${XT_DOMA_CONFIG_NAME}` during parsing of recipes.
This commit fixes a warning that appears during parsing of
recipes if XT_DOMA_CONFIG_NAME is not defined.
Signed-off-by: Ruslan Shymkevych <ruslan_shymkevych@epam.com>
=> dom0: handle absence of XT_DOMA_CONFIG_NAME

meta-xt-dom0/recipes-kernel/linux/linux-generic-armv8.bbappend, meta-xt-domx/recipes-core/dbus/dbus-cxx_0.10.0.bb, meta-xt-driver-domain/recipes-extended/xt-log/xt-log_git.bb
Use https instead of git because unauthenticated git protocol is disabled by github
Signed-off-by: Ihor Usyk <ihor_usyk@epam.com>
=> URIs: replace git protocol with https one for the github sources.

meta-xt-domx/recipes-extended/xen/xen-source.inc, meta-xt-driver-domain/recipes-extended/displaymanager/displaymanager_git.bb
This is the backport of the some useful patches from https://github.com/xen-troops/meta-xt-common/pull/31 MR, which adds hardknott release to meta-xt-common
=> Backporting useful changes from hardknott release MR

meta-xt-control-domain/conf/layer.conf, meta-xt-dom0/conf/layer.conf, meta-xt-domu/conf/layer.conf, meta-xt-domx/conf/layer.conf, meta-xt-driver-domain/conf/layer.conf
To make sure that specific components can override/redefine settings from more generic levels, we set the following priorities for levels:
```
meta-xt-common     -  8
meta-xt-<platform> - 10
meta-xt-<product>  - 12
```
Signed-off-by: Ruslan Shymkevych <ruslan_shymkevych@epam.com>
=> Set priority of layers to 8

meta-xt-domx/recipes-graphics/wayland/weston-init.bbappend
weston-init: remove ivi shell configuration as it is platform-specifiс
IVI setting should be applied in hardware-specific or product layers,
but not in common code.
=> weston-init: remove ivi shell configuration as it is platform-specifiс

meta-xt-control-domain/recipes-guest/domu/files/domu.service, meta-xt-driver-domain/recipes-graphics/images/core-image-weston.bbappend
The use-case appeared, for which we need to disable installation of the
displbe and sndbe services for a specific product.
For this purpose, we remove default installation of those services,
making it a product-specific decision on whether to install them or
not.
This patch is intended to remove dependencies to displbe and sndbe from
the common meta-layers.
=> distro-features: Remove deps to displbe and sndbe

meta-xt-control-domain/recipes-guest/doma/doma.bb, meta-xt-control-domain/recipes-guest/doma/u-boot-android-bazel_1.0.0.bb
For the virtio builds we want to use a recent origin Android U-Boot.
This patch introduces a u-boot-android-bazel.bb, which is used to build original Android U-Boot.
=> u-boot: Switch virtio builds to origin Android U-boot

meta-xt-qemu/recipes-qemu/qemu/qemu.inc
It was identified, that personal repo was used as the source for the QEMU package. This patch switches QEMU SRC_URI to xen-troops.
=> qemu: Switch to xen-troops SRC_URI

meta-xt-control-domain/recipes-guest/doma/doma.bb, meta-xt-control-domain/recipes-guest/domu/domu.bb
If dtb is not required for dom-u or dom-a corresponding variables 'XT_DOMU_DTB_NAME' or 'XT_DOMA_DTB_NAME' will not be defined in *.yaml configuration. In this case we should test content of these variables in recipe files where corresponding dtbs are installed to avoid their installation.
=> dom-0: implement support of empty dtb paths

meta-xt-control-domain/recipes-guest/domz/domz.bb
Variable XT_DOMZ_CONFIG_NAME is not defined if Zephyr is not used as guest.
For that reason we have to add XT_DOMZ_CONFIG_NAME to SRC_URI conditionaly, to avoid warning during parsing of recipes.
=> domz: fix usage of XT_DOMZ_CONFIG_NAME

meta-xt-driver-domain/recipes-connectivity/xen-network/files/bridge-up-notification.service
This commit is cherry-picked as-is from the `dunfell` branch with `Acked-by`.
---
This commit makes `bridge-up-notification` dependant on `network.target` instead of `networkd-wait-online.service`. That change allows to run bridge when network management stack is up, and avoid situation when guest domain is not starting because network is not connected or not configured properly.
According to the documentation, we should use just `After=network.target`, because this is a passive unit.
Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>
=> [Port to master] xen-network: wait for network.target

meta-xt-control-domain/recipes-guest/doma/u-boot-android-bazel_1.0.0.bb
Transition U-Boot to the xen-troops repository is
required to facilitate the implementation of virtio blk. This is necessitated by the absence of two crucial patches in the Android repository. The switch will be in effect until full upstream integration is achieved.
=> doma: update manifest branch with xen-troops based u-boot

meta-xt-control-domain/recipes-guest/domu/domu.bb
If we do not use DomU then XT_DOMU_CONFIG_NAME is not defined. This results in attempt to calculate CRC for incorrect file `file://${XT_DOMU_CONFIG_NAME}` during parsing of recipes.
This commit fixes a warning that appears during parsing of recipes if XT_DOMU_CONFIG_NAME is not defined.
=> dom0: handle absence of XT_DOMU_CONFIG_NAME

meta-xt-control-domain/recipes-guest/doma/u-boot-android-bazel_1.0.0.bb
In the case of a virtio build, the configuration for virtio-blk will be chosen. In other cases, the configuration for pvblock will be chosen.
=> doma: choose U-Boot config with respect to build type

meta-xt-driver-domain/recipes-connectivity/xen-network/xen-network.bb
"\n" handling is wildly varies between shells. Some shells replace it with line feed, other just print it as is (i.e. literally \n). This causes hard to debug issues with the build. This particular case led to the following error:
```
ERROR: Logfile of failure stored in: /home/lorc/work/prod-devel-salvator-8g/yocto/build-domd/tmp/work/salvator_x-poky-linux/core-image-weston/1.0-r0/temp/log.do_image.1535569
Log data follows:
| DEBUG: Executing python function do_image
| NOTE: Executing systemd_preset_all ...
| DEBUG: Executing shell function systemd_preset_all
| ln -s /lib/systemd/system/systemd-userdbd.socket /home/lorc/work/prod-devel-salvator-8g/yocto/build-domd/tmp/work/salvator_x-poky-linux/core-image-weston/1.0-r0/rootfs/etc/systemd/system/so
ckets.target.wants/systemd-userdbd.socket …
```
=> xen-network.bb: don't use "\n" in echo command

meta-xt-driver-domain/recipes-extended/virtio-disk/virtio-disk.bb
Although the virtio-disk is not fully integrated, there is already recipe which allows to build the backend, so correct it to point to actual sources.
=> virtio-disk: Use proper branch for the backend

meta-xt-domu/recipes-core/images/common_install.inc, meta-xt-domu/recipes-core/images/core-image-minimal.bbappend, meta-xt-domu/recipes-graphics/images/core-image-weston.bbappend, meta-xt-driver-domain/recipes-core/images/common_install.inc, meta-xt-driver-domain/recipes-core/images/core-image-minimal.bbappend, meta-xt-driver-domain/recipes-graphics/images/core-image-weston.bbappend
This commit adds possibility to build our components inside core-image-minimal.
Parts that are common for core-image-minimal and core-image-weston are moved into the common_install.inc file.
=> domd: domu: add support for core-image-minimal

meta-xt-control-domain-virtio/recipes-guest/domu/domu.bbappend, meta-xt-control-domain-virtio/recipes-guest/domu/files/virtio-env-no-weston.conf, meta-xt-control-domain-virtio/recipes-guest/domu/files/virtio-env-weston.conf, meta-xt-control-domain-virtio/recipes-guest/domu/files/virtio-env.conf, meta-xt-driver-domain-virtio/recipes-extended/xen/xen-tools_git.bbappend
- dom0: virtio: use weston-up as an optional drop-in for DomU
- dom0: virtio: add dependency for no wayland use case in DomU
- domd: virtio: install weston-env.conf optionally
This PR have to be merged only after https://github.com/xen-troops/meta-xt-prod-devel-rcar/pull/126 because we need
`gsx` MACHINE_FEATURE to be defined in Dom0.
=> Add possibility to run virtio without weston

meta-xt-qemu/recipes-qemu/qemu/qemu.inc
According to the documentation:
https://docs.yoctoproject.org/bitbake/2.0/bitbake-user-manual/bitbake-user-manual-fetching.html#git-submodule-fetcher-gitsm
the yocto method involves using gitsm instead of manual scripts. The 'submodules=1' option has been removed because it is not recognized.
=> qemu: use the yocto method to fetch git submodules

meta-xt-security/conf/layer.conf, meta-xt-security/recipes-security/optee/optee-client.inc, meta-xt-security/recipes-security/optee/optee-client/tee-supplicant.sh, meta-xt-security/recipes-security/optee/optee-client/tee-supplicant@.service, meta-xt-security/recipes-security/optee/optee-client_4.1.0.bb, meta-xt-security/recipes-security/optee/optee-examples.inc, meta-xt-security/recipes-security/optee/optee-examples_4.1.0.bb, meta-xt-security/recipes-security/optee/optee-os-tadevkit_4.1.0.bb, meta-xt-security/recipes-security/optee/optee-os.inc, meta-xt-security/recipes-security/optee/optee-os/0003-optee-enable-clang-support.patch, meta-xt-security/recipes-security/optee/optee-os_4.1.0.bb, meta-xt-security/recipes-security/optee/optee-test.inc, meta-xt-security/recipes-security/optee/optee-test/0001-xtest-stats-remove-unneeded-stat.h-include.patch, meta-xt-security/recipes-security/optee/optee-test/run-ptest, meta-xt-security/recipes-security/optee/optee-test_4.1.0.bb, meta-xt-security/recipes-security/optee/optee.inc
Add meta-xt-security layer that hosts OP-TEE-related recipes. Those recipes were taken from meta-arm. We can't use meta-arm directly, because it depends on meta-arm-toolchain and we are not ready to switch the toolchain for all our products.
This is only partial copy of meta-arm/recipes-security, because original also includes recipes for Trusted Services and we don't need them yet.
=> meta-xt-security: introduce the layer / add OP-TEE recipes

meta-xt-control-domain/recipes-guest/doma/u-boot-android-bazel_1.0.0.bb
u-boot-android-bazel directly calls Bazel inside do_compile. At the same time, the Bazel build spawns client and server instances, which use sockets for communication. Enable the network for this use-case, which is disabled by default.
=> doma: enable network in do_compile for u-boot-android-bazel

meta-xt-control-domain/recipes-guest/doma/u-boot-android-bazel_1.0.0.bb, meta-xt-domx/recipes-core/dbus/dbus-cxx_0.10.0.bb, meta-xt-domx/recipes-extended/xen/xen-source.inc, meta-xt-driver-domain/recipes-extended/camerabe/camerabe_git.bb, meta-xt-driver-domain/recipes-extended/displaymanager/displaymanager_git.bb, meta-xt-driver-domain/recipes-extended/displbe/displbe_git.bb, meta-xt-driver-domain/recipes-extended/libxenbe/libxenbe_git.bb, meta-xt-driver-domain/recipes-extended/sndbe/sndbe_git.bb, meta-xt-driver-domain/recipes-extended/virtio-disk/virtio-disk.bb, meta-xt-driver-domain/recipes-extended/xt-log/xt-log_git.bb, meta-xt-qemu/recipes-qemu/qemu/qemu.inc
- SRCREV is fixed for all components
- 'tag' is replaced with SRCREV for dbus-cxx to have consistent approach
- SRCREV is added for the android_u-boot_manifest repo
=> Fix SRCREV for all components

meta-xt-driver-domain/recipes-connectivity/xen-network/xen-network.bb, meta-xt-driver-domain/recipes-extended/block/block.bb, meta-xt-driver-domain/recipes-extended/camerabe/camerabe_git.bb, meta-xt-driver-domain/recipes-extended/displbe/displbe_git.bb, meta-xt-driver-domain/recipes-extended/sndbe/sndbe_git.bb, meta-xt-driver-domain/recipes-extended/virtio-disk/virtio-disk.bb
The `RRECOMMENDS` is used to extend the usability and should is used to list packages that are not required, but nice to have. But `xenstore` is critical for the backends.
At the same time, we see that all backends have `RDEPENDS = xen-tools-xenstore` and this is the proper solution.
So, this commit removes useless `RRECOMMENDS = virtual/xenstored` from backend recipes.
=> backends: remove `RRECOMMENDS = virtual/xenstored`

meta-xt-control-domain/recipes-guest/doma/u-boot-android-bazel_1.0.0.bb
There is no need to `inherit base` because this bbclass is implicitly inherited by all recipes.
=> dom0: remove base.bbclass from doma's u-boot

meta-xt-security/recipes-security/optee/optee-client_4.2.0.bb, meta-xt-security/recipes-security/optee/optee-os-tadevkit.inc, meta-xt-security/recipes-security/optee/optee-os-tadevkit_4.1.0.bb, meta-xt-security/recipes-security/optee/optee-os-tadevkit_4.2.0.bb, meta-xt-security/recipes-security/optee/optee-os_4.2.0.bb, meta-xt-security/recipes-security/optee/optee-test_4.2.0.bb
Other products will use v4.1.0 because of absence of `.bbappends` witch   `COMPATIBLE_MACHINE` for new version.
Build tested for salvator-x-8gb.
=> Add recipes for OP-TEE v4.2.0 as it is required by RPI5 product

meta-xt-driver-domain/recipes-connectivity/xen-network/xen-network.bb
Enhance support for fastboot over the network by
implementing correct port 5554 forwarding.
=> doma: add fastboot port forwarding

meta-xt-control-domain/recipes-guest/domd/files/domd.service
Currently, due to race conditions, xenstore and xenconsole services may start after launching DomD and as a result, starting DomD fails. Adding proper systmemd dependencies fixes this issue.
=> dom0: add missing dependencies to start DomD
